version: '3'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5001:5000"  # Changed to port 5001
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

