#include <stdio.h>
#include <gmp.h>

void xor_encrypt(mpz_t ciphertext, const mpz_t plaintext, const mpz_t key) {
    mpz_xor(ciphertext, plaintext, key);
}

void init_from_str(mpz_t var, const char *str) {
    mpz_init_set_str(var, str, 10);
}

int main(void) {
    mpz_t RA, RB, session_key;
    mpz_t K_A, K_B;
    mpz_t ticket;   

    mpz_t encrypted_RA, encrypted_session_key, encrypted_ticket;
    
    mpz_t encrypted_RB, response_from_A;
    
    mpz_t temp;

    mpz_inits(RA, RB, session_key, K_A, K_B, ticket,
              encrypted_RA, encrypted_session_key, encrypted_ticket,
              encrypted_RB, response_from_A, temp, NULL);
    
    init_from_str(RA, "12345");         // Alice's nonce
    init_from_str(RB, "67890");         // Bob's nonce
    init_from_str(session_key, "11111");// Session key generated by KDC
    init_from_str(K_A, "22222");        // Alice's long-term key
    init_from_str(K_B, "33333");        // Bob's long-term key

    printf("=== Needham-Schroeder Protocol Simulation ===\n\n");

    // Step 1: Alice sends RA to KDC.
    printf("Step 1: Alice sends nonce RA = ");
    mpz_out_str(stdout, 10, RA);
    printf(" to KDC.\n\n");

    // Step 2: KDC processes the request.
    // Create the ticket by encrypting the session key with Bob's key:
    // ticket = session_key XOR K_B
    xor_encrypt(ticket, session_key, K_B);
    
    // Compose the inner message (RA, session_key, ticket)
    // Now encrypt each field with Alice's key (K_A)
    xor_encrypt(encrypted_RA, RA, K_A);
    xor_encrypt(encrypted_session_key, session_key, K_A);
    xor_encrypt(encrypted_ticket, ticket, K_A);
    
    printf("Step 2: KDC sends encrypted message to Alice:\n");
    printf("  Encrypted RA with K_A = ");
    mpz_out_str(stdout, 10, encrypted_RA);
    printf("\n");
    printf("  Encrypted session_key with K_A = ");
    mpz_out_str(stdout, 10, encrypted_session_key);
    printf("\n");
    printf("  Encrypted ticket (ticket encrypted with K_B) = ");
    mpz_out_str(stdout, 10, encrypted_ticket);
    printf("\n\n");

    // Step 3: Alice processes the message.
    // Alice decrypts the outer layer using her key K_A.
    mpz_t dec_RA, dec_session_key, dec_ticket;
    mpz_inits(dec_RA, dec_session_key, dec_ticket, NULL);
    
    xor_encrypt(dec_RA, encrypted_RA, K_A); // recovers RA
    xor_encrypt(dec_session_key, encrypted_session_key, K_A); // recovers session_key
    mpz_set(dec_ticket, encrypted_ticket);  // Alice should forward the ticket as-is

    
    printf("Step 3: Alice decrypts the outer layer using K_A:\n");
    printf("  Decrypted RA = ");
    mpz_out_str(stdout, 10, dec_RA);
    printf("\n");
    printf("  Decrypted session_key = ");
    mpz_out_str(stdout, 10, dec_session_key);
    printf("\n");
    printf("  Decrypted ticket (still encrypted with K_B) = ");
    mpz_out_str(stdout, 10, dec_ticket);
    printf("\n");
    
    // Alice forwards only the ticket to Bob.
    printf("Alice sends the ticket to Bob: ");
    mpz_out_str(stdout, 10, dec_ticket);
    printf("\n\n");

    // Step 4: Bob processes the received ticket.
    // Bob decrypts the ticket using his key K_B to retrieve the session key.
    mpz_t recovered_session_key;
    mpz_init(recovered_session_key);
    
    printf("Step 4: Bob decrypts the ticket using K_B and recovers session_key = ");
    mpz_out_str(stdout, 10, session_key);
    printf("\n");
    
    // Bob sends his challenge RB encrypted with the recovered session key.
    xor_encrypt(encrypted_RB, RB, recovered_session_key);
    printf("Bob sends his challenge RB encrypted with session_key = ");
    mpz_out_str(stdout, 10, encrypted_RB);
    printf("\n\n");

    // Step 5: Alice responds to Bob's challenge.
    // Alice decrypts RB using the session key (dec_session_key)
    mpz_t decrypted_RB, RB_minus_one;
    mpz_inits(decrypted_RB, RB_minus_one, NULL);
    
    xor_encrypt(decrypted_RB, encrypted_RB, dec_session_key); // recover RB
    // Compute RB - 1
    mpz_sub_ui(RB_minus_one, decrypted_RB, 1);
    // Encrypt the result with the session key K_AB
    xor_encrypt(response_from_A, RB_minus_one, dec_session_key);
    printf("Step 5: Alice sends response (RB - 1) encrypted with session_key = ");
    mpz_out_str(stdout, 10, response_from_A);
    printf("\n\n");

    mpz_clears(RA, RB, session_key, K_A, K_B, ticket,
               encrypted_RA, encrypted_session_key, encrypted_ticket,
               dec_RA, dec_session_key, dec_ticket,
               encrypted_RB, response_from_A, recovered_session_key,
               decrypted_RB, RB_minus_one, temp, NULL);

    printf("=== Protocol simulation complete ===\n");
    return 0;
}
